cubes:
  - name: achats
    sql_table: dbt.fct_achat

    joins:
      - name: fournisseurs
        sql: "{CUBE}.fournisseur_id = {fournisseurs.fournisseur_id}"
        relationship: many_to_one
      - name: produits
        sql: "{CUBE}.produit_id = {produits.produit_id}"
        relationship: many_to_one
      - name: routes_achat
        sql: "{CUBE}.route_id = {routes_achat.route_id}"
        relationship: many_to_one

    measures:
      - name: count_po
        type: count
        description: "Nombre de lignes d'achats"

      - name: montant_total_achats
        type: sum
        sql: (quantite_commandee * cout_unitaire)

      - name: total_quantite_commandee
        type: sum
        sql: quantite_commandee

      - name: total_quantite_recue
        type: sum
        sql: quantite_recue

      - name: cout_transport_total
        type: sum
        sql: cout_transport_alloue

      - name: delai_reception_moyen
        type: avg
        sql: delai_livraison_jours

    dimensions:
      - name: ligne_po_id
        sql: ligne_po_id
        type: number
        primary_key: true

      - name: fournisseur_id
        sql: fournisseur_id
        type: number

      - name: produit_id
        sql: produit_id
        type: number

      - name: statut_commande
        sql: statut_commande
        type: string

      - name: devise_achat
        sql: devise_achat
        type: string

      - name: date_commande
        sql: date_commande
        type: time

      - name: date_reception
        sql: date_reception
        type: time

views:
  - name: vue_analyse_achats
    cubes:
      - join_path: achats
        includes:
          - count_po
          - montant_total_achats
          - total_quantite_commandee
          - total_quantite_recue
          - cout_transport_total
          - delai_reception_moyen
          - statut_commande
          - date_commande
      - join_path: achats.fournisseurs
        includes:
          - nom_fournisseur
          - pays_fournisseur
      - join_path: achats.produits
        includes:
          - nom_produit
          - categorie