views:
  - name: achats_view
    description: >
      Vue des achats : volumes de commandes, dépenses, suivi des réceptions
      et performance des fournisseurs et des routes logistiques.

    cubes:
      - join_path: achats
        prefix: false
        includes: "*"

      - join_path: achats.fournisseurs
        prefix: true
        includes: "*"

      - join_path: achats.produits
        prefix: true
        includes: "*"

      - join_path: achats.routes_achat
        prefix: true
        includes: "*"
        
      - join_path: achats.fournisseurs.villes
        prefix: true
        includes: "*"