views:
  - name: achats_view
    cubes:
      - join_path: fct_achat
        includes:
          - total_montant_achat
          - ligne_po_id
      - join_path: fct_achat.fournisseurs
        includes:
          - nom_fournisseur
          - pays_fournisseur