views:
  - name: clients_view
    description: >
      Vue des clients : analyse du portefeuille clients, segmentation,
      localisation géographique et historique des ventes associées.

    cubes:
      - join_path: clients
        prefix: false
        includes: "*"

      - join_path: clients.villes
        prefix: true
        includes: "*"

      - join_path: clients.ventes
        prefix: true
        includes: "*"