views:
  - name: clients_geo_view
    description: >
      Vue des indicateurs géographiques et logistiques par client : ville,
      segment, commandes, quantités livrées et retards de livraison.

    cubes:
      - join_path: fct_geo_clients
        prefix: false
        includes: "*"

      - join_path: fct_geo_clients.villes
        prefix: true
        includes: "*"
