views:
  - name: fournisseurs_geo_view
    description: >
      Vue des routes logistiques géographiques par fournisseur : villes
      d'origine et d'entrepôt, mode de transport, délais et coûts
      d'expédition.

    cubes:
      - join_path: fct_geo_fournisseurs
        prefix: false
        includes: "*"
