views:
  - name: produits_view
    description: >
      Vue des produits : référentiel des articles, prix de base, coûts,
      marge théorique et suivi des ventes et achats associés.

    cubes:
      - join_path: produits
        prefix: false
        includes: "*"

      - join_path: produits.ventes
        prefix: true
        includes: "*"

      - join_path: produits.achats
        prefix: true
        includes: "*"

      - join_path: produits.stock_journalier
        prefix: true
        includes: "*"